konveyor/cpma

.gitignore, config.json, cpma.go
SSH connect and session using only key
Use JSON configuration file
=> SSH with key and JSON config

cpma.go, sftpclient/getfile.go
Added sftclient package to carry remote file retrieval operation
=> Dedicated internal pkg for sftp client

cpma.go, env/env.go, internal/log/log.go
=> implement custom formatter

.gitignore, cmd/root.go, cpma.go, env/env.go
Thus allowing to disconnect the fetch process
and being able to use files downloaded separately
Also breaks SrCluster and DsCluster into respective ClusterV3 and ClusterV4 structures.
=> Adds LoadSrc to load config files locally

examples/cpma-config.example.yaml
=> update example config

Makefile, README.md, cmd/root.go, go.mod, go.sum, ocp3config/ocp3.go, ocp3config/ocp3_test.go, ocp4crd/oauth/oauth.go, ocp4crd/oauth/oauth_test.go, test/test-master-config.yaml
This PR introduces basic unit tests for testing out config migration logic.
=> Add basic unit tests and minor refactoring

cmd/root.go, ocp3config/ocp3.go, ocp4/oauth/github.go, ocp4/oauth/github_test.go, ocp4/oauth/htpasswd.go, ocp4/oauth/htpasswd_test.go, ocp4/oauth/oauth.go, ocp4/oauth/oauth_test.go, ocp4/ocp4.go, ocp4/secrets/secrets.go
Also adds a secret YAML file example.
TODO: add tests for secrets
=> Adds OCP4 structure to integrate CR OAuth and Secrets

.gitignore, env/env.go, env/logfile.go, ocp3/ocp3.go, ocp4/oauth/github_test.go, ocp4/oauth/htpasswd_test.go, ocp4/oauth/oauth.go, ocp4/secrets/secrets.go
=> Streamline logger, Update TODO/FIXUPs, Small CodeFixes.

ocp4/oauth/oauth.go, ocp4/oauth/oauth_test.go, test/oauth/bulk-test-master-config.yaml
Also change order of OAuth components to place them in
alphabetical order as we've a long list coming
=> Added missing call for GitLab in OAuth bulk test

cmd/root.go
=> Event loop

ocp4/oauth/basicauth.go, ocp4/oauth/basicauth_test.go, ocp4/oauth/oauth.go, ocp4/oauth/oauth_test.go, ocp4/secrets/secrets.go, ocp4/secrets/secrets_test.go, test/oauth/basicauth-test-master-config.yaml, test/oauth/bulk-test-master-config.yaml
This PR is based on https://github.com/fusor/cpma/pull/62, I'll rebase after it gets merged.
=> Basic auth provider support

ocp4/oauth/oauth.go, ocp4/oauth/oauth_test.go, ocp4/oauth/openid.go, ocp4/oauth/openid_test.go, test/oauth/bulk-test-master-config.yaml, test/oauth/openid-test-master-config.yaml
I moved common logic from switch statement in oauth.go. What do you think @gildub @arapov ?
I'll rebase after previous PR gets merged.
=>  Move common logic from switch state

cmd/root.go
Resolves issue https://github.com/fusor/cpma/issues/78
=> Removes event loop

examples/cpma-config.example.yaml, ocp3/ocp3.go, ocp3/ocp3_test.go
Fixes https://github.com/fusor/cpma/issues/76
=> Add ability to use different master and node config paths

cmd/root.go, internal/sftpclient/sftpclient.go, ocp/ocp.go, ocp3/ocp3.go, ocp3/ocp3_test.go, ocp4/oauth/basicauth_test.go, ocp4/oauth/github.go, ocp4/oauth/github_test.go, ocp4/oauth/gitlab_test.go, ocp4/oauth/google_test.go, ocp4/oauth/htpasswd_test.go, ocp4/oauth/keystone_test.go, ocp4/oauth/ldap_test.go, ocp4/oauth/oauth_test.go, ocp4/oauth/openid_test.go, ocp4/oauth/requestheader_test.go, ocp4/ocp4.go, ocp4/ocp4_test.go
The OCP struct and methods wrap all OCP3, OCP4 data for each file
and provide the architecture to handle the workflow to generate
OCDs manifests
=> Provides OCP structure

Makefile, pkg/ocp/ocp.go, pkg/ocp4/ocp4.go, pkg/ocp4/ocp4_test.go, pkg/ocp4/sdn/sdn.go
This is a basic setup for migrating SDN config, I will add tests for it in next PR.
=> Add support for SDN config migration

README.md
The IO directory structure was not properly formatted.
=> Add preformat tag around the directory structure

Makefile
This turns on lint and vet for travis.
=> Add lint vet to ci target

Makefile
Reverts fusor/cpma#145
Travis needs to have the golint bin installed.
=> Revert "Add lint vet to ci target"

pkg/transform/manifest_output.go, pkg/transform/oauth/oauth.go, pkg/transform/oauth/oauth_test.go, pkg/transform/oauth_transform_test.go, pkg/transform/registries_transform_test.go, pkg/transform/sdn_transform_test.go, pkg/transform/testdata/bulk-test-master-config.yaml, pkg/transform/testdata/registries.conf, pkg/transform/transform.go
=> Add oauth, sdn, and registries transform unit test

pkg/env/env_test.go, pkg/transform/oauth/basicauth_test.go, pkg/transform/oauth/github_test.go, pkg/transform/oauth/gitlab_test.go, pkg/transform/oauth/google_test.go, pkg/transform/oauth/htpasswd_test.go, pkg/transform/oauth/keystone_test.go, pkg/transform/oauth/ldap_test.go, pkg/transform/oauth/oauth_test.go, pkg/transform/oauth/openid_test.go, pkg/transform/oauth/requestheader_test.go, pkg/transform/oauth_transform_test.go, pkg/transform/registries_transform_test.go, pkg/transform/sdn_transform_test.go, pkg/transform/secrets/secrets.go, pkg/transform/secrets/secrets_test.go
This PR should make our tests more structured.
Closes #111
=> Refactor tests

pkg/config/config.go, pkg/config/decode/decode.go, pkg/transform/oauth_transform.go, pkg/transform/registries_transform.go, pkg/transform/sdn_transform.go, pkg/transform/transform.go
Closes https://github.com/fusor/cpma/issues/154
Helps with https://github.com/fusor/cpma/issues/133  by getting Fetch() outside of transform.go.
=> Config own package

pkg/transform/configmaps/configmaps.go, pkg/transform/configmaps/configmaps_test.go, pkg/transform/configmaps/testdata/expected-configmap.yaml, pkg/transform/oauth/basicauth.go, pkg/transform/oauth/basicauth_test.go, pkg/transform/oauth/github.go, pkg/transform/oauth/github_test.go, pkg/transform/oauth/gitlab.go, pkg/transform/oauth/gitlab_test.go, pkg/transform/oauth/google.go, pkg/transform/oauth/google_test.go, pkg/transform/oauth/htpasswd.go, pkg/transform/oauth/htpasswd_test.go, pkg/transform/oauth/keystone.go, pkg/transform/oauth/keystone_test.go, pkg/transform/oauth/ldap.go, pkg/transform/oauth/ldap_test.go, pkg/transform/oauth/oauth.go, pkg/transform/oauth/oauth_test.go, pkg/transform/oauth/openid.go, pkg/transform/oauth/openid_test.go, pkg/transform/oauth/requestheader.go, pkg/transform/oauth/requestheader_test.go, pkg/transform/oauth/testdata/bulk-test-master-config.yaml, pkg/transform/oauth/testdata/expected-bulk-test-masterconfig-oauth.yaml, pkg/transform/oauth_transform.go, pkg/transform/oauth_transform_test.go, pkg/transform/testdata/bulk-test-master-config.yaml, pkg/transform/transform.go
I will add tests and fix CI in next commit
Closes https://github.com/fusor/cpma/issues/155
=> Create config map for oauth providers CA

pkg/transform/oauth/basicauth.go, pkg/transform/oauth/basicauth_test.go, pkg/transform/oauth/github.go, pkg/transform/oauth/github_test.go, pkg/transform/oauth/gitlab.go, pkg/transform/oauth/gitlab_test.go, pkg/transform/oauth/google.go, pkg/transform/oauth/keystone.go, pkg/transform/oauth/keystone_test.go, pkg/transform/oauth/ldap.go, pkg/transform/oauth/ldap_test.go, pkg/transform/oauth/oauth_test.go, pkg/transform/oauth/requestheader.go, pkg/transform/oauth/requestheader_test.go, pkg/transform/oauth/testdata/expected-omit-empty-masterconfig-oauth.yaml, pkg/transform/oauth/testdata/omit-empty-master-config.yaml, pkg/transform/oauth_transform_test.go
This PR is based on https://github.com/fusor/cpma/pull/170, I'll rebase after it gets merged.
Closes https://github.com/fusor/cpma/issues/169
=>  Omit empty values for oauth provider

pkg/transform/oauth/basicauth.go, pkg/transform/oauth/github.go, pkg/transform/oauth/gitlab.go, pkg/transform/oauth/google.go, pkg/transform/oauth/htpasswd.go, pkg/transform/oauth/keystone.go, pkg/transform/oauth/openid.go, pkg/transform/secrets/secrets.go, pkg/transform/secrets/secrets_test.go
Fixed tests after changes, updated usage of the `GenSecret` function. This PR closes #158.
=> Changed type of secretType parametr to enum.

pkg/transform/oauth/github.go, pkg/transform/oauth/gitlab.go, pkg/transform/oauth/google.go, pkg/transform/oauth/openid.go
Closes https://github.com/fusor/cpma/issues/172
=> Return on error in secret creation

pkg/env/env.go
=> Ask to create config if it wasn't found

go.mod, go.sum, pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/env/env.go
=> Add cluster discovery feature

cmd/root.go, pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/env/env.go
`--console-logs` is only for our dev purpose, by default logs should not be in console
Closes https://github.com/fusor/cpma/issues/195
=> Hide logs from console by default

pkg/transform/sdn_transform.go
https://github.com/fusor/cpma/issues/199
=> Add new config parts to SDN report

cmd/root.go, examples/cpma-config.example.yaml, pkg/io/remotehost/remotehost.go
Closes https://github.com/fusor/cpma/issues/203
I didn't include insecure key, because it's mainly for our dev purpose. 
@jmontleon Can you check if it works for you?
=> Allow insecure host key

pkg/env/env.go
Require ssh key and cluster name and ask port after login
https://github.com/fusor/cpma/issues/216
=> Require ssh key and cluster hostname

go.mod, pkg/transform/configmaps/configmaps.go, pkg/transform/crio_transform.go, pkg/transform/crio_transform_test.go, pkg/transform/oauth/basicauth.go, pkg/transform/oauth/github.go, pkg/transform/oauth/gitlab.go, pkg/transform/oauth/google.go, pkg/transform/oauth/htpasswd.go, pkg/transform/oauth/keystone.go, pkg/transform/oauth/ldap.go, pkg/transform/oauth/oauth.go, pkg/transform/oauth/openid.go, pkg/transform/oauth/requestheader.go, pkg/transform/oauth/types.go, pkg/transform/registries_transform.go, pkg/transform/registries_transform_test.go, pkg/transform/sdn/sdn.go, pkg/transform/sdn/testdata/expected-network-cr-master.yaml, pkg/transform/sdn_transform_test.go, pkg/transform/secrets/secrets.go, pkg/transform/testdata/expected-bulk-test-masterconfig-oauth.yaml, pkg/transform/testdata/expected-configmap.yaml, pkg/transform/testdata/expected-omit-empty-masterconfig-oauth.yaml, pkg/transform/testdata/expected-secret.yaml, pkg/transform/transform.go
This is a first step that will allow us to start using the openshift v1 structs and remove the ones we've created by hand. 
Those structs use json tags so we need to use a yaml library that will respect those instead of yaml tags since we need to print yaml
=> use ghodds yaml

pkg/transform/sdn/sdn.go, pkg/transform/sdn/sdn_test.go, pkg/transform/sdn_transform.go
Seems like we left that one behind
=> SDN: use transform.GenYAML

.travis.yml, pkg/api/initclient.go, pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/env/env.go
Initializing k8s api client in separate package should help us reusing code, later we'll have other parts of CPMA that require api usage
=> Init k8s api client in a separate package

pkg/transform/oauth_transform_test.go, pkg/transform/testdata/expected-CR-configmap-basicauth.yaml, pkg/transform/testdata/expected-CR-configmap-github.yaml, pkg/transform/testdata/expected-CR-configmap-gitlab.yaml, pkg/transform/testdata/expected-CR-configmap-keystone.yaml, pkg/transform/testdata/expected-CR-configmap-ldap.yaml, pkg/transform/testdata/expected-CR-configmap-requestheader.yaml, pkg/transform/testdata/expected-CR-oauth.yaml, pkg/transform/testdata/expected-CR-secret-github123456789-secret.yaml, pkg/transform/testdata/expected-CR-secret-gitlab123456789-secret.yaml, pkg/transform/testdata/expected-CR-secret-google123456789123456789.yaml, pkg/transform/testdata/expected-CR-secret-htpasswd_auth.yaml, pkg/transform/testdata/expected-CR-secret-keystone_provider-client-cert.yaml, pkg/transform/testdata/expected-CR-secret-my_keystone_provider-client-key.yaml, pkg/transform/testdata/expected-CR-secret-my_openid_connect.yaml, pkg/transform/testdata/expected-CR-secret-my_remote_basic_auth_provider-client-cert-secret.yaml, pkg/transform/testdata/expected-CR-secret-my_remote_basic_auth_provider-client-key-secret.yaml, pkg/transform/testdata/expected-report-oauth.json
https://github.com/fusor/cpma/issues/228
=> Oauth test load

pkg/transform/image_transform.go, pkg/transform/testdata/expected-report-image.json
Restores the value in the report which is now visible in the comment field per current approach.
=> Fix registry report

cmd/root.go, pkg/env/env.go
https://github.com/fusor/cpma/issues/237
=> Output dir set '.' as default

pkg/transform/oauth/basicauth.go, pkg/transform/oauth/github.go, pkg/transform/oauth/gitlab.go, pkg/transform/oauth/google.go, pkg/transform/oauth/htpasswd.go, pkg/transform/oauth/keystone.go, pkg/transform/oauth/openid.go, pkg/transform/oauth/testdata/basicauth/expected-CR-oauth.yaml, pkg/transform/oauth/testdata/github/expected-CR-oauth.yaml, pkg/transform/oauth/testdata/gitlab/expected-CR-oauth.yaml, pkg/transform/oauth/testdata/google/expected-CR-oauth.yaml, pkg/transform/oauth/testdata/htpasswd/expected-CR-oauth.yaml, pkg/transform/oauth/testdata/keystone/expected-CR-oauth.yaml, pkg/transform/oauth/testdata/openid/expected-CR-oauth.yaml, pkg/transform/oauth_transform_test.go, pkg/transform/secrets/secrets.go, pkg/transform/testdata/expected-CR-oauth.yaml, pkg/transform/testdata/expected-CR-secret-basicauth-client-cert-secret.yaml, pkg/transform/testdata/expected-CR-secret-basicauth-client-key-secret.yaml, pkg/transform/testdata/expected-CR-secret-github-secret.yaml, pkg/transform/testdata/expected-CR-secret-gitlab-secret.yaml, pkg/transform/testdata/expected-CR-secret-google.yaml, pkg/transform/testdata/expected-CR-secret-htpasswd.yaml, pkg/transform/testdata/expected-CR-secret-keystone-client-cert.yaml, pkg/transform/testdata/expected-CR-secret-keystone-client-key.yaml, pkg/transform/testdata/expected-CR-secret-openid.yaml, pkg/transform/testdata/expected-master_config-oauth-bulk.yaml, pkg/transform/testdata/expected-master_config-oauth-omit-empty-values.yaml
Sometimes generated secrets don't have valid names, this PR should fix it https://github.com/fusor/cpma/issues/243
=> Validate secret names

pkg/transform/oauth/basicauth_test.go, pkg/transform/oauth/github_test.go, pkg/transform/oauth/gitlab_test.go, pkg/transform/oauth/google_test.go, pkg/transform/oauth/htpasswd_test.go, pkg/transform/oauth/keystone_test.go, pkg/transform/oauth/ldap_test.go, pkg/transform/oauth/oauth.go, pkg/transform/oauth/oauth_test.go, pkg/transform/oauth/openid_test.go, pkg/transform/oauth/requestheader_test.go, pkg/transform/oauth/templates.go, pkg/transform/oauth/templates_test.go, pkg/transform/oauth/testdata/templates/expected-CR-oauth.yaml, pkg/transform/oauth/testdata/templates/master_config.yaml, pkg/transform/oauth_transform.go, pkg/transform/oauth_transform_test.go, pkg/transform/testdata/expected-CR-oauth.yaml, pkg/transform/testdata/expected-CR-secret-templates-error-secret.yaml, pkg/transform/testdata/expected-CR-secret-templates-login-secret.yaml, pkg/transform/testdata/expected-CR-secret-templates-providerselect-secret.yaml, pkg/transform/testdata/master_config-bulk.yaml, pkg/transform/transform_test.go, pkg/utils/test/load_test_data.go
Add translation of templates that allow to customize the login page.
Closes https://github.com/fusor/cpma/issues/197
=> Add translation of OAuth templates

pkg/env/env.go
https://github.com/fusor/cpma/issues/259
=> React on interrupt signal

go.mod, go.sum, pkg/api/initclient.go, pkg/api/openshift.go, pkg/api/requests.go, pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/env/env.go, pkg/env/env_test.go, pkg/transform/cluster_report_transform.go, pkg/transform/report_output.go
https://github.com/fusor/cpma/issues/255
=> Openshift API client and Routes List

README.md, cmd/root.go, examples/cpma-config.example.yaml, pkg/env/env.go, pkg/env/env_test.go, pkg/env/testdata/cpma-config.yml, pkg/io/io.go
Closes https://github.com/fusor/cpma/issues/262
=> Clean up parameters

pkg/transform/oauth/basicauth.go, pkg/transform/oauth/github.go, pkg/transform/oauth/gitlab.go, pkg/transform/oauth/google.go, pkg/transform/oauth/htpasswd.go, pkg/transform/oauth/keystone.go, pkg/transform/oauth/ldap.go, pkg/transform/oauth/oauth.go, pkg/transform/oauth/openid.go, pkg/transform/oauth/requestheader.go
Looks like multiple values returned when building identity provider could be stored in one structure, because in some cases one function was returning 5 values.
=> Return one structure instead of multiple values

pkg/env/env_test.go, pkg/transform/api_transform_test.go, pkg/transform/configmaps/configmaps_test.go, pkg/transform/crio_transform_test.go, pkg/transform/etcd_transform_test.go, pkg/transform/oauth/basicauth_test.go, pkg/transform/oauth/github_test.go, pkg/transform/oauth/gitlab_test.go, pkg/transform/oauth/google_test.go, pkg/transform/oauth/htpasswd_test.go, pkg/transform/oauth/keystone_test.go, pkg/transform/oauth/ldap_test.go, pkg/transform/oauth/oauth_test.go, pkg/transform/oauth/openid_test.go, pkg/transform/oauth/requestheader_test.go, pkg/transform/oauth/templates_test.go, pkg/transform/scheduler/scheduler_test.go, pkg/transform/sdn/sdn_test.go, pkg/transform/sdn_transform_test.go, pkg/transform/secrets/secrets_test.go, pkg/transform/transform_test.go
Not that tests are taking a long time, but this is trying to boost them or at least has the merit at looking how we can do it.
=> Parallelization of some tests

pkg/io/remotehost/remotehost.go
After @gildub introduced usage of singleton in creating openshift api client, I thought we need to improve SSH client initialization. Before this change SSH client was created on every call of RunCMD() that happens for almost every report part.
Before this PR:
```
ademicev-OSX:cpma ademicev$ for i in {1..10}; do rm -rf data/; time ./bin/cpma; done
real	0m22.988s
real	0m22.996s
real	0m24.163s
real	0m23.540s
real	0m24.463s
real	0m24.171s
real	0m28.652s
real	0m25.328s
real	0m29.044s
real	0m20.973s
```
After this PR:
```
ademicev-OSX:cpma ademicev$ for i in {1..10}; do rm -rf data/; time ./bin/cpma; done
real	0m14.686s
real	0m16.343s
real	0m14.628s
real	0m12.796s
real	0m17.193s
real	0m15.767s
real	0m17.181s
real	0m15.362s
real	0m14.522s
real	0m16.072s
```
=> Init ssh client only on first call

pkg/transform/api_transform_test.go, pkg/transform/crio_transform_test.go, pkg/transform/etcd_transform_test.go, pkg/transform/sdn_transform_test.go, pkg/transform/transform_test.go
This should fix the inconsistent behavior.
=> Fixes potential resource races for parallel tests

pkg/transform/docker_transform.go, pkg/transform/report_output.go
In case there is an issue with remote connection. Closes #276
=> Stopping docker transform from report generation.

pkg/transform/cluster/cluster.go, pkg/transform/cluster/cluster_test.go, pkg/transform/cluster_report_transform.go, pkg/transform/cluster_report_transform_test.go, pkg/transform/report_output.go, pkg/transform/testdata/expected-report-cluster.json, pkg/utils/test/load_test_cluster_report.go
I refactored cluster report to make it more testable and added tests
=> Cluster report: Refactor and adding tests

pkg/api/openshift.go, pkg/api/requests.go, pkg/transform/cluster/cluster.go, pkg/transform/cluster/cluster_test.go, pkg/transform/cluster_report_transform.go, pkg/transform/cluster_report_transform_test.go, pkg/transform/internal/test/load_test_cluster_report.go, pkg/transform/report_output.go, pkg/transform/testdata/expected-report-cluster.json
Adds k8s resource quotas and openshift cluster quotas
=> Cluster Report: Add Quota

docs/scenarios/report/README.md, docs/scenarios/report/report-example.json
This PR is an initial step in documenting CPMA workflows.
=> Add report docs

pkg/transform/cluster_transform.go, pkg/transform/cluster_transform_test.go, pkg/transform/clusterquota/clusterquota.go, pkg/transform/internal/test/load_test_cluster_report.go, pkg/transform/quota/quota.go, pkg/transform/testdata/expected-CR-cluster-quota.yaml, pkg/transform/testdata/expected-CR-resource-quota.yaml
This extends cluster_transform  (thus the file rename) to generate CRs as well.
Close https://github.com/fusor/cpma/issues/256
=> Cluster Resource Quotas and Resource Quotas manifests

README.md, cmd/root.go, pkg/env/env.go, pkg/env/env_test.go, pkg/env/testdata/cpma-config.yml, pkg/transform/api_transform.go, pkg/transform/api_transform_test.go, pkg/transform/cluster_transform.go, pkg/transform/cluster_transform_test.go, pkg/transform/crio_transform.go, pkg/transform/docker_transform.go, pkg/transform/etcd_transform.go, pkg/transform/image_transform.go, pkg/transform/oauth_transform.go, pkg/transform/project_transform.go, pkg/transform/scheduler_transform.go, pkg/transform/sdn_transform.go, pkg/transform/transform.go, test/e2e/e2e_test.go
Closes https://github.com/fusor/cpma/issues/310
=> Options to filter manifests or reports modes

pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/env/env.go
Closes https://github.com/fusor/cpma/issues/319
=> Add ability to select kubeconfig context

pkg/transform/cluster/cluster_test.go, pkg/transform/cluster_transform_test.go, pkg/transform/internal/test/load_test_cluster_report.go, pkg/transform/quota/quota_test.go
https://github.com/fusor/cpma/issues/271
=> Resource Quota: Translate unit tests 

pkg/transform/clusterquota/clusterquota_test.go
https://github.com/fusor/cpma/issues/271
=> ClusterResourceQuota unit test for Translate

pkg/transform/cluster/cluster.go, pkg/transform/cluster/cluster_test.go, pkg/transform/internal/test/load_cluster.go, pkg/transform/testdata/expected-report-cluster.json
Closes https://github.com/fusor/cpma/issues/337
=> Add SCC - Namespace dependency to report

README.md
Also adds links to OCP documentation
=> Paragraph about authorizations

pkg/transform/cluster/cluster.go
Closes https://github.com/fusor/cpma/issues/348
=> Skip namespace if it doesn't have roles

Makefile, cmd/version.go
https://bugzilla.redhat.com/show_bug.cgi?id=1741771
=> Provide Build Version and Time

pkg/transform/reportoutput/staticpage/js/custom.js, pkg/transform/reportoutput/staticpage/templates/namespaces.gohtml, pkg/transform/reportoutput/testdata/reportexpected.html
This PR: 
Breaks down the namespaces with sub trees.
For empty table cells sets text to "None".
Closes https://github.com/fusor/cpma/issues/358
=>  Break down the namespaces with sub trees

pkg/api/requests.go, pkg/transform/cluster/cluster.go, pkg/transform/cluster/cluster_test.go, pkg/transform/cluster_transform.go, pkg/transform/internal/test/load_cluster.go, pkg/transform/reportoutput/html.go, pkg/transform/reportoutput/staticpage/templates/namespaces.gohtml, pkg/transform/reportoutput/testdata/reportexpected.html, pkg/transform/testdata/expected-report-cluster.json
This PR adds PVC to html/json report
Closes https://github.com/fusor/cpma/issues/356
=> Add PVC to html/json report

pkg/transform/cluster/cluster.go
Close https://github.com/fusor/cpma/issues/369
=> [Report:ReportPVCs] fixes invalid memory address or nil pointer dereference for NFS PV with no StorageClass 

Makefile
Alternatively we could use pushd/popd but that's seemed overkill.
=> Use alternative cd cmd in Makefile

pkg/transform/crio_transform.go, pkg/transform/transform.go
Closes  https://github.com/fusor/cpma/issues/372
=> Transform error handling: use warning instead of error

pkg/transform/quota/quota.go, pkg/transform/quota/quota_test.go, pkg/transform/testdata/expected-CR-resource-quota.yaml
Closes https://bugzilla.redhat.com/show_bug.cgi?id=1745978
=> Resourcequota version is v1

docs/README.md
Closes https://github.com/fusor/cpma/issues/336
=> More context for transforms

pkg/io/io.go
By checking if the file exists first allows for ssh session errors to not be caught into file retrieval step.
=> SSH fetchfile: check file exists first for better error mgt

README.md, cmd/root.go, cmd/root_test.go, pkg/env/env_test.go
Closes https://github.com/fusor/cpma/issues/381
=> Document silent mode

pkg/env/env.go, pkg/env/env_test.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1748058
=> Make sure hostname is queried in local mode

pkg/api/requests.go, pkg/transform/cluster/cluster.go, pkg/transform/internal/test/load_cluster.go
Address https://bugzilla.redhat.com/show_bug.cgi?id=1748173
=> Deployment and DaemonSet to use v1beta1 API

.travis.yml
Since all deps are vendored, let's make sure building with them doesn't fail.
=> Make travis use vendored deps

pkg/io/io.go
Fix https://github.com/fusor/cpma/issues/382
=> Check local file exists firt

pkg/api/requests.go, pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/transform/cluster_transform.go
Early tests have shown a faster running time by a factor of 2.
=> Concurent api requests

.travis.yml, README.md, cpma.spec, go.mod, pkg/env/env_test.go, pkg/io/io.go, pkg/transform/oauth/github.go
Update with bug, documentation fixes, RPM spec file.
=> Release 1.0 update bundle

pkg/api/requests.go, pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/transform/cluster_transform.go
* Concurent api requests
* Using logrus.Fatal() instead of panic()
(cherry picked from commit 1ecba8c681b62cc24e8dcbdbbd04373600ade715)
=> Concurent api requests (#399)

go.mod, pkg/transform/oauth/github.go, pkg/transform/testdata/expected-master_config-oauth-omit-empty-values.yaml, pkg/transform/testdata/master_config-omit-empty-values.yaml
Address https://bugzilla.redhat.com/show_bug.cgi?id=1748174
=> OAuth github: Filter out when organization, teams are missing

go.mod, pkg/transform/oauth/github.go, pkg/transform/testdata/expected-master_config-oauth-omit-empty-values.yaml, pkg/transform/testdata/master_config-omit-empty-values.yaml
(cherry picked from commit 542c3d13abe25ff94adc7c81edcd0af5b8a7f996)
=> [Release-1.0] Backport - OAuth github: Filter out when organizations, teams are missing (#404)

pkg/transform/oauth/github.go
(cherry picked from commit 232f21abbe66f332cca2395bcd66a7828694839a)
=> OAuth Github: Mapping method is optional (#405)

pkg/env/clusterdiscovery/clusterdiscovery.go
This PR stop further panics due to change in the version of survey.
=> Stop Survey panic for AskOne function

pkg/transform/oauth_transform.go, pkg/transform/testdata/expected-report-oauth.json
(cherry picked from commit 15ccff729661fb402cb12672d313fd20763c5f48)
=> Report about OpenId Issuer field (#414)

cpma.spec
(cherry picked from commit 70d042a2031902f5a1cb1d0bf997e70cdfa74395)
=> Update RPM spec to fix rpmlint issues (#416)

pkg/transform/configmaps/configmaps.go, pkg/transform/configmaps/configmaps_test.go, pkg/transform/oauth/basicauth.go, pkg/transform/oauth/github.go, pkg/transform/oauth/gitlab.go, pkg/transform/oauth/keystone.go, pkg/transform/oauth/ldap.go, pkg/transform/oauth/oauth.go, pkg/transform/oauth/requestheader.go, pkg/transform/oauth_transform.go, pkg/transform/testdata/expected-CR-configmap-basicauth.yaml, pkg/transform/testdata/expected-CR-configmap-github.yaml, pkg/transform/testdata/expected-CR-configmap-gitlab.yaml, pkg/transform/testdata/expected-CR-configmap-keystone.yaml, pkg/transform/testdata/expected-CR-configmap-ldap.yaml, pkg/transform/testdata/expected-CR-configmap-requestheader.yaml, pkg/transform/testdata/expected-CR-configmap.yaml, pkg/transform/transform.go, pkg/transform/transform_test.go
Partly addresses  https://bugzilla.redhat.com/show_bug.cgi?id=1760875
=> ConfigMaps use k8s definition; data uses ca.crt

pkg/transform/oauth/basicauth.go, pkg/transform/testdata/expected-CR-secret-basicauth-client-cert-secret.yaml, pkg/transform/testdata/expected-CR-secret-basicauth-client-key-secret.yaml
(cherry picked from commit 5857bbcc1c13b987241f1c5b6bac43f42f98045c)
=> BasicAuth provider secret: specific names for data fields (#423)

pkg/api/initclient.go
Protobuf is more efficient and this also clearly state the client
=> API: Use protobuf

pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/env/env.go
While working at adding a destination cluster for future feature I discovered some redundant code.
=> Cleanse survey hostname api

pkg/api/initclient.go, pkg/api/k8s.go, pkg/api/requests.go, pkg/env/env.go, pkg/transform/cluster_transform.go
- Adds discovery client
- Adds `discovery.ListGroupVersions` API request
- Augments `api.Resources` with list of cluster's GroupVersion
=> Add discovery and get GroupVersionList

pkg/transform/sdn/sdn.go
https://bugzilla.redhat.com/show_bug.cgi?id=1762273
=> Fix host prefix value

cpma.spec
(cherry picked from commit 54211c91ebf79baad773f0556da60354fb5c6b85)
=> add dist tag to RPM spec (#429)

pkg/api/initclient.go
(cherry picked from commit e51986ffbd1050c251832cb4c0b3df10a252f06f)
=> API: Use protobuf (#430)

pkg/api/initclient.go, pkg/api/k8s.go, pkg/api/openshift.go
* refactor singleton API client initialization
* Rely on k8s and openshift libs for init or die
(cherry picked from commit 8a65ff7ed39ef74e55681aa3467e6c76b2f132b4)
=> Api init refactor (#432)

pkg/transform/sdn/sdn.go
(cherry picked from commit cc92e478f6faf930d0e81ef2f20a06e0d3bec0d4)
=> Fix host prefix value (#442)

pkg/api/requests.go
This reverts commit 34635b863ca2d673afa9f231305cc21ce7a8676c.
This is not a supported feature
=> Revert "Adds Horizontal Pod Autoscaler list from AutoscalingV1 (#441)"

pkg/api/initclient.go, pkg/api/k8s.go, pkg/api/requests.go, pkg/env/env.go, pkg/transform/cluster_transform.go
This reverts commit 65f1f92e32929bf98217139f537d51e7d4574573.
Final revert to remove discovery and GroupVersion reporting which are an unsupported feature.
=> Revert "Add discovery and get GroupVersionList (#433)"

pkg/api/openshift.go
This has been applied to master too but as part of patch which didn't make it to this branch
=> Renames user1 import to userv1

cmd/root.go, pkg/api/initclient.go, pkg/env/clusterdiscovery/clusterdiscovery.go, pkg/env/env.go, pkg/env/testdata/cpma-config.yml, test/e2e/e2e_test.go
This finalize clean-up of this feature which is out of scope.
=> Cleanup after discovery and GVs removal
