konveyor/cpma

cmd/root.go
cpma.go
env/env.go
internal/sftpclient/sftpclient.go

this is helpful for
- defining the output directory for extracted control plane
configuration in general
- as well as to run the tool in the loop against various target
control planes and save the output in a respective directories

Add -o --output-dir option

---

cmd/root.go
env/env.go

Current dir is the default for the output.

set the default outputDir and make it OS agnostic

---

ocp4/oauth/htpasswd.go
ocp4/oauth/keystone.go
ocp4/oauth/keystone_test.go
ocp4/oauth/oauth.go
ocp4/oauth/oauth_test.go
ocp4/secrets/secrets.go
ocp4/secrets/secrets_test.go
test/oauth/bulk-test-master-config.yaml
test/oauth/keystone-test-master-config.yaml

I made secret generation more flexible and covered it with tests.
Keystone auth misses file fetching, same as htpasswd now.

Add keystone oauth, secrets refactor and tests

---

cmd/root.go
ocp4/oauth/oauth.go
ocp4/oauth/oauth_test.go
ocp4/ocp4.go
ocp4/secrets/secrets.go
ocp4/secrets/secrets_test.go

CRD manifests need to be consumable by openshift-installer as locally generated YAML files

Manifests are dumped locally

---

ocp4/oauth/basicauth_test.go
ocp4/oauth/github_test.go
ocp4/oauth/gitlab_test.go
ocp4/oauth/google_test.go
ocp4/oauth/htpasswd_test.go
ocp4/oauth/keystone_test.go
ocp4/oauth/ldap_test.go
ocp4/oauth/oauth.go
ocp4/oauth/oauth_test.go
ocp4/oauth/openid_test.go
ocp4/oauth/requestheader_test.go
ocp4/ocp4.go
ocp4/ocp4_test.go
ocp4/secrets/secrets.go
ocp4/secrets/secrets_test.go

Must be "Metadata" for Go and "metadata" for YAML but not MetaData and metaData respectively

Fix metada wrong case

---

pkg/ocp4/oauth/htpasswd.go
pkg/ocp4/oauth/htpasswd_test.go
pkg/ocp4/oauth/keystone.go
pkg/ocp4/oauth/keystone_test.go
pkg/ocp4/oauth/oauth.go
pkg/ocp4/oauth/oauth_test.go
pkg/ocp4/ocp4_test.go

This is used for fetching any xtra file discovered when parsing config.
Initially used by htpasswd and keystone.

Fetch xtra file

---

README.md
internal/io/io.go
internal/io/sftpclient/sftpclient.go
pkg/ocp/ocp.go
pkg/ocp4/oauth/oauth.go
pkg/ocp4/oauth/oauth_test.go

- Allows user to download cluster's configuration files and use them directly.
- Speeds up dev times
To force network file fetch just remove any prior data, for instance:
`rm -rf ./data/*`
Added to readme accordingly. 
Works around https://github.com/fusor/cpma/issues/31

Config files retrieved locally if available

---

cmd/root.go
pkg/ocp/ocp.go

This only moves the core operations out of root.go.
https://github.com/fusor/cpma/issues/114

root.go is not core application

---

pkg/transform/transform.go

Should log the file we're attempting to Fetch prior to running GetFile. I was running this and it was trying to get a file that didn't exist, and I had no idea exactly what file was missing, because the error would tank the program before it logged the file.

Log file fetch attempt before running GetFile

---

pkg/transform/oauth_transform.go
pkg/transform/registries_transform.go
pkg/transform/sdn_transform.go
pkg/transform/transform.go

Having a method named `Type` suggests this might have something to do with actual data types. It's actually used as a method to provide a human readable identifier for an error string, so I think it makes sense to be more specific with the method name.

Change transform.Type to transform.Name

---

pkg/transform/oauth/basicauth.go
pkg/transform/oauth/github.go
pkg/transform/oauth/gitlab.go
pkg/transform/oauth/google.go
pkg/transform/oauth/htpasswd.go
pkg/transform/oauth/keystone.go
pkg/transform/oauth/ldap.go
pkg/transform/oauth/oauth.go
pkg/transform/oauth/openid.go
pkg/transform/oauth/requestheader.go

Closes #157 
Changes:
* Error processing in all oauth transform files.
* Some variable regrouping, adding error propagation to `buildRequestHeaderIP` and `buildLdapIP`.

Added error propagation to oauth transform.

---

pkg/io/io.go
pkg/transform/oauth/htpasswd_test.go
pkg/transform/oauth/keystone_test.go
pkg/transform/oauth/oauth.go
pkg/transform/oauth/oauth_test.go

The tests doen't make use of the mock function. 
Meanwhile we can still override io.GetFile if needed in the future.

Make io.GetFile pure func and remove unused mock

---

pkg/transform/oauth/requestheader.go
pkg/transform/oauth/testdata/expected-omit-empty-masterconfig-oauth.yaml
pkg/transform/oauth/testdata/omit-empty-master-config.yaml

EmailHeaders, NameHeaders and PrefferedUsernameHeaders were changed to optional, as it is stated in https://docs.openshift.com/container-platform/3.11/install_config/configuring_authentication.html#RequestHeaderIdentityProvider

Added ommiting optional headers from RequestHeader

---

pkg/io/io.go

Fix wrong path introduced by https://github.com/fusor/cpma/pull/184

IO: Fix path after remote file fetch

---

cmd/root.go

After report PR was merged CPMA has no additional arguments, it should return error with `usage` message on invalid commands. 
Logger should be initialized before config, because `InitConfig` uses logrus

Error on invalid commands

---

cmd/root.go
pkg/env/env.go

This PR introduces ability to get config values from CLI arguments,  as an alternative to prompting and yaml file.
`./bin/cpma --source master-0.ademicev3112.lab.rdu2.cee.redhat.com --login root --key /Users/ademicev/.ssh/quicklab.key --port 22 -o ./data`

Get config values from CLI arguments

---

pkg/env/env.go

This was being printed before the file logger was set up so the message does not appear as expected.

Fix debug mode message

---

pkg/env/env.go
pkg/env/env_test.go
pkg/env/loghooks.go

I introduced usage of logrus hooks to handle log final output:
1. All logs will always be sent to cpma.log.json
2. Error logs will always appear in console, so user can get reason of cpma failure without checking log file.
3. All will appear in terminal if `--console-logs` flag was set

Use logrus hooks to handle log output

---

pkg/transform/sdn_transform.go

This PR adds ingress config to SDN report.
I don't think we can migrate it, because the definition of CR for configuring cluster-ingress-operator in OCP4, is using `domain`:
```
apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
name: cluster
spec:
domain: apps.openshiftdemos.com
```
In OCP3 we are working with `ingressIPNetworkCIDR` in network config
```
networkConfig:
clusterNetworks:
- cidr: 10.128.0.0/14 
hostSubnetLength: 9 
externalIPNetworkCIDRs: null
hostSubnetLength: 9
ingressIPNetworkCIDR: 172.29.0.0/16
networkPluginName: redhat/openshift-ovs-multitenant 
serviceNetworkCIDR: 172.30.0.0/16
```
I am not sure if domain can represent a CIDR notation, because notation can include a range of IP addresses, but my knowledge is very limited in this area. …

Add ingress config to SDN report

---

pkg/transform/oauth/basicauth_test.go
pkg/transform/oauth/github_test.go
pkg/transform/oauth/gitlab_test.go
pkg/transform/oauth/google_test.go
pkg/transform/oauth/htpasswd_test.go
pkg/transform/oauth/keystone_test.go
pkg/transform/oauth/ldap_test.go
pkg/transform/oauth/oauth.go
pkg/transform/oauth/oauth_test.go
pkg/transform/oauth/openid_test.go
pkg/transform/oauth/requestheader_test.go
pkg/transform/oauth_transform.go
pkg/transform/oauth_transform_test.go
pkg/transform/testdata/expected-bulk-test-masterconfig-oauth.yaml
pkg/transform/testdata/expected-omit-empty-masterconfig-oauth.yaml
pkg/transform/transform_test.go

We can translate `accessTokenMaxAgeSeconds` in token config and append it to oAuthCR, 
but `authorizeTokenMaxAgeSeconds` became unavailable for user.
https://github.com/openshift/cluster-authentication-operator/blob/6ae1bd829bfeccc2b5beafa98315211c8deb2da0/pkg/operator2/oauth.go#L138
https://docs.openshift.com/container-platform/3.11/install_config/configuring_authentication.html#token-options

Add translate and report for oAuth token config

---

pkg/env/env.go
pkg/transform/crio_transform.go
pkg/transform/crio_transform_test.go
pkg/transform/report_output.go
pkg/transform/testdata/crio.conf
pkg/transform/transform.go

crio.conf is unlikely to exist in many clusters as docker was the default runtime, so it's very likely unless you add a crio.conf that you'll see a warning that the file cannot be downloaded.
If it does exist however normal processing should occur.

add crio transform

---

pkg/transform/docker_transform.go
pkg/transform/docker_transform_test.go
pkg/transform/transform.go

It's technically possible to have just crio installed in a 3.x cluster, so it may be worth looking for a file owned by the docker package to see if it's installed (and likely being used), but as far as I know the only way to determine if either or both is in use is by looking at the labels for all nodes, so I'm not sure that gives us the full picture either.

Add docker report

---

pkg/transform/oauth_transform.go
pkg/transform/oauth_transform_test.go
pkg/transform/sdn_transform.go
pkg/transform/sdn_transform_test.go

This PR improves report, in my opinion some parts of report don't properly match master config yaml.
I think if yaml looks like this:
```
tokenConfig:
accessTokenMaxAgeSeconds: 123
authorizeTokenMaxAgeSeconds: 123
```
`Name` field in report should match `accessTokenMaxAgeSeconds` and `Kind` should be `tokenConfig` so report json will look like this:
```
{
"name": "AccessTokenMaxAgeSeconds",
"kind": "TokenConfig",
"supported": true,
"confidence": "green",
"comment": ""
},
{
"name": "AuthorizeTokenMaxAgeSeconds",
"kind": "TokenConfig",
"supported": false,
"confidence": "red",
"comment": "Translation of AuthorizeTokenMaxAgeSeconds is not supported, it's value is 5 minutes in OCP4"
}
```

Improve report messages

---

pkg/decode/decode.go
pkg/io/io.go
pkg/transform/oauth/basicauth.go
pkg/transform/oauth/github.go
pkg/transform/oauth/gitlab.go
pkg/transform/oauth/google.go
pkg/transform/oauth/htpasswd.go
pkg/transform/oauth/keystone.go
pkg/transform/oauth/ldap.go
pkg/transform/oauth/oauth.go
pkg/transform/oauth/oauth_test.go
pkg/transform/oauth/openid.go
pkg/transform/oauth/requestheader.go
pkg/transform/sdn/sdn.go
pkg/transform/sdn/sdn_test.go
pkg/transform/sdn_transform.go
pkg/transform/transform_test.go
pkg/utils/test/load_test_data.go

The main reason for renaming the package identifier is to avoid future confusion when importing the config/v1.

Rename configv1 to legacyconfigv1

---

Dockerfile

I thought registry.access.redhat.com was depricated and didn't realize I was authenticated when I tested the build so this needs to be changed to fixed in order for Quay builds to be able to pull the base image to work.
https://bugzilla.redhat.com/show_bug.cgi?id=1719994#c3
https://bugzilla.redhat.com/show_bug.cgi?id=1719994#c4
Basically registry.access.redhat.com isn't going away any time soon specifically because of UBI.

Use an unauthenticated registry for ubi so Quay builds work

---

pkg/transform/image/image.go
pkg/transform/image_transform.go
pkg/transform/testdata/expected-report-image.json

The following parameters are not supported in OCP4:
- AdditionalTrustedCA 
- MaxImagesBulkImportedPerRepository
- MaxScheduledImageImportsPerMinute
- ScheduledImageImportMinimumIntervalSeconds
Also beautified `pkg/transform/testdata/expected-report-image.json`

Image unsupported param

---

pkg/transform/oauth/basicauth.go
pkg/transform/oauth/basicauth_test.go
pkg/transform/oauth/github.go
pkg/transform/oauth/github_test.go
pkg/transform/oauth/gitlab.go
pkg/transform/oauth/gitlab_test.go
pkg/transform/oauth/google.go
pkg/transform/oauth/google_test.go
pkg/transform/oauth/htpasswd.go
pkg/transform/oauth/htpasswd_test.go
pkg/transform/oauth/keystone.go
pkg/transform/oauth/keystone_test.go
pkg/transform/oauth/ldap.go
pkg/transform/oauth/ldap_test.go
pkg/transform/oauth/oauth.go
pkg/transform/oauth/oauth_test.go
pkg/transform/oauth/openid.go
pkg/transform/oauth/openid_test.go
pkg/transform/oauth/requestheader.go
pkg/transform/oauth/requestheader_test.go
pkg/transform/oauth_transform.go
pkg/transform/testdata/expected-CR-oauth.yaml
pkg/transform/testdata/expected-master_config-oauth-bulk.yaml
pkg/transform/testdata/expected-master_config-oauth-omit-empty-values.yaml
pkg/transform/transform.go
pkg/transform/transform_test.go
pkg/utils/test/load_test_data.go

After changes introduced in this PR, OAuth manifest will look like this:
```
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
creationTimestamp: null
name: cluster
namespace: openshift-config
spec:
identityProviders:
- htpasswd:
fileData:
name: htpasswd_auth-secret
mappingMethod: claim
name: htpasswd_auth
type: HTPasswd
templates:
error:
name: ""
login:
name: ""
providerSelection:
name: ""
tokenConfig:
accessTokenMaxAgeSeconds: 86400
status: {}
```
There is one issue I see: we can't omit empty entries like `templates`, I will try to deploy OCP4 using this and fix CI if deployment succeeds.

Use configv1 structures for oauth

---

pkg/env/env.go

If log file is not JSON valid then let's not call it such.
Re todo comment, well the file name is static for now.

Remove comments and json suffixe to log file

---

pkg/transform/cluster_report_transform.go
pkg/transform/report_output.go

Based on [#231](https://github.com/fusor/cpma/pull/231), closes #251.
- Added info about PV capacity, driver and phase.
- Added node list to output, which contains resource information.
- Master nodes are listed with other nodes by boolean value.
Sample output:
- Nodes: 
```
"nodes": [
{
"name": "ip-10-1-1-245.eu-central-1.compute.internal",
"masterNode": true,
"resources": {
"cpu": "4",
"memoryConsumed": "100Mi",
"memoryCapacity": "16265188Ki",
"runningPods": "30",
"podCapacity": "250"
}
}
],
...
```
- PVs:
```
"pvs": [
{
"name": "pv1",
"driver": {
"nfs": {
"server": "127.0.0.1",
"path": "/var/lib/nfs/exports/pv1"
}
},
"capacity": {
"storage": "10G"
},
"phase": "Available"
},
...
```

Extended cluster report

---

pkg/transform/cluster_report_transform.go
pkg/transform/report_output.go

Closes #253. Every namespace has a report of used resources.
```
"namespaces": [
{
"name": "default",
"latestChange": "2019-06-28T23:47:07Z",
"resources": {
"containerCount": 4,
"cpuSummary": "3",
"memSummary": "640Mi"
},
...
```

Added report for pod resources, related to namespaces.

---

pkg/io/io.go
pkg/io/remotehost/remotehost.go

https://github.com/fusor/cpma/issues/31
Also refactored `io.FetchEnv` to use `remotehost.RunCMD`

Replaces SFTP with SSH command to retrieve files

---

pkg/api/requests.go
pkg/transform/cluster_report_transform.go

Moved from usage of map for `NamespaceResources`, to additional parametr for `NamespaceResources`, describing the name of related namespace. Should be presorted now. Closes #280 and unblocks #252.

Usage of list instead of map in requests.go (Refactor)

---

pkg/env/env.go

Added `CPMA` prefix to avoid mess with predefined env variables.
Now it is possible for example to `export CPMA_HOSTNAME=<cluster_hostname>` and not care about feeding those variables manually.
TODO: implications

[WIP] Fix for env variables support in Viper.

---

cmd/root.go
pkg/api/initclient.go
pkg/env/clusterdiscovery/clusterdiscovery.go
pkg/env/env.go
pkg/env/testdata/cpma-config.yml
pkg/io/io.go

Closes https://github.com/fusor/cpma/issues/278
If ssh is not available, we ask user for source of config files, local or remote. If remote then we keep them same workflow we have right now, if local then just use survey to get paths listed here.
This PR also adds ability for user to choose how API client should be created, using cluster name from current context or prompt.
I will try to add tests for `survey` inputs later and update README after review.
Local files as source:
Remote files:

Use local config files

---

pkg/io/io.go
pkg/io/io_test.go
pkg/io/remotehost/remotehost.go
pkg/io/testdata/local-file

Adds tests to cover FetchFile(fetchFromRemote and FetchFromLocal), FetchEnv and FetchStringSource
Also refactored fetchFromRemote which was (historically) fetching file from local first. This is not needed anymore since fetchFromLocal is used by FetchFile.

Test for io pkg

---

.gitignore
cmd/root.go
examples/cpma-config.example.yaml
pkg/api/initclient.go
pkg/env/env.go
pkg/env/env_test.go
pkg/env/testdata/cpma-config.yml
pkg/io/remotehost/remotehost.go

- Fixed logic in retrival of config variables.
- Removed nested ssh values.
- Now every variable from config could be defined as following.
| ENV variable               | Config equivalent    |
|----------------------------|----------------------|
| CPMA_CLUSTERNAME           | clustername          |
| CPMA_SSHPORT               | sshport              |
| CPMA_CREATECONFIG          | createconfig         |
| CPMA_OUTPUTDIR             | outputdir            |
| CPMA_SSHPRIVATEKEY         | sshprivatekey        |
| CPMA_LOGIN                 | login                |
| CPMA_CONFIGSOURCE          | configsource         |
| CPMA_PASSWD                | passwd               |
| CPMA_HOSTNAME              | hostname             |
| CPMA_SSHLOGIN              | sshlogin             |
| …

Config arguments rearrangement

---

cpma_test.go

There isn't much to test in main package, meanwhile `TestMain` (since go 1.4 [1]) allows to setup environment if needed. This might be handy for CI.
[1] https://justinas.org/my-reason-to-be-excited-for-go-14

Add TestMain

---

README.md
cmd/root.go
examples/cpma-config.example.yaml
pkg/env/env.go
pkg/env/env_test.go
pkg/env/testdata/cpma-config.yml
pkg/io/io.go
pkg/transform/manifest_output.go

This also renames "OutputDir" to "WorkDir".
`WorDir` is the base when working in `Local` mode in which case files will be searched under the `hostname`.

Local feature use OutputDir for application working dir

---

pkg/api/requests.go
pkg/transform/cluster/cluster.go
pkg/transform/cluster_report_transform.go
pkg/transform/cluster_report_transform_test.go
pkg/transform/internal/test/load_test_cluster_report.go
pkg/transform/testdata/expected-report-cluster.json

Closes #294.
Sample output:
```
"daemonSets": [
{
"name": "apiserver",
"latestChange": "2019-07-10T09:51:47Z"
},
...
"deployments": [
{
"name": "metrics-server",
"latestChange": "2019-07-10T09:48:16Z"
}
```
Other changes:
- Minor fixes in pointer arithmetic (Refactor)
- Added tests.

Extending cluster report with DS and Deploynments.

---

pkg/env/env.go
pkg/env/env_test.go

Having warn log level in error hook will be useful. This way connections timeouts or info about skipped report/translate parts will be visible by default.
Closes https://github.com/fusor/cpma/issues/270

Add warn log level to error hook

---

pkg/api/initclient.go
pkg/api/k8s.go
pkg/api/openshift.go

> I think now CPMA started to become more analytics than translation tool and API clients are crucial here. Let's `panic` in case of error and rename function to `newOpenshiftOrDie()`, this way it will be more obvious, for someone new, that creating API can panic.
https://github.com/fusor/cpma/issues/272

Die on api client creation fail and small refactor

---

pkg/io/io.go
pkg/io/io_test.go

When cpma is working with local host it should obtain local env variables.

Fetch env variable from local host

---

pkg/transform/api_transform.go
pkg/transform/api_transform_test.go
pkg/transform/cluster_transform.go
pkg/transform/cluster_transform_test.go
pkg/transform/crio_transform.go
pkg/transform/crio_transform_test.go
pkg/transform/docker_transform.go
pkg/transform/docker_transform_test.go
pkg/transform/etcd_transform.go
pkg/transform/etcd_transform_test.go
pkg/transform/image_transform.go
pkg/transform/image_transform_test.go
pkg/transform/oauth_transform.go
pkg/transform/oauth_transform_test.go
pkg/transform/project_transform.go
pkg/transform/project_transform_test.go
pkg/transform/report_output.go
pkg/transform/reportoutput/html.go
pkg/transform/reportoutput/json.go
pkg/transform/reportoutput/output.go
pkg/transform/reportoutput/templates/report_template.go
pkg/transform/scheduler_transform.go
pkg/transform/scheduler_transform_test.go
pkg/transform/sdn_transform.go
pkg/transform/sdn_transform_test.go
pkg/transform/transform.go

Since we are in feature freeze PR will go to a separate branch for now.
After some discussion, we decided that will be nice to support multiple report output formats: json, html, maybe pdf in future etc. 
This PR introduces 3 things: 
1. Improvement of writing report to json file.
Our current process of writing report to json file creates a json file before the transforms starts and then opens the file and appends a new report for every config part we have, this means the json file is opened, unmarshalled, marshalled a lot of times. 
I refactored this part, now all reports are collected and final report is passed to output function, report json is created only in case when report format is set to json and file is opened only once.
2. Adds support for multiple output formats.
I added new …

Support for multiple output formats

---

cmd/root.go
cmd/root_test.go
pkg/env/env.go
pkg/transform/cluster/cluster.go
pkg/transform/cluster_transform.go
pkg/transform/oauth/oauth.go
pkg/transform/reportoutput/html.go
pkg/transform/reportoutput/json.go
pkg/transform/sdn_transform.go
pkg/transform/transform.go

This PR replaces `--verbose` with `--silent` and improves info warning log level.
Example of logs after this PR:
```
ademicev-OSX:cpma ademicev$./bin/cpma
INFO[27 Aug 19 09:33 CEST] Starting manifest and report generation
INFO[27 Aug 19 09:33 CEST] Finished transforming - API
INFO[27 Aug 19 09:33 CEST] Flushing manifests to disk
INFO[27 Aug 19 09:33 CEST] CRD:Added: data/manifests/100_CPMA-cluster-quota-resource-for-user.yaml
INFO[27 Aug 19 09:33 CEST] Finished transforming - ClusterReport
WARN[27 Aug 19 09:33 CEST] Skipping Crio: No configuration file available
INFO[27 Aug 19 09:33 CEST] Finished transforming - Docker
INFO[27 Aug 19 09:33 CEST] Finished transforming - ETCD
INFO[27 Aug 19 09:33 CEST] Flushing manifests to disk
INFO[27 Aug 19 09:33 CEST] CRD:Added: …
```

Replace verbose with silent and improve logging

---

go.mod
pkg/transform/oauth/github.go

In order to avoid any GitHub user to authenticate to a cluster, organizations or teams value(s) must be provided. This is only the case of non enterprise GitHub.
Address https://bugzilla.redhat.com/show_bug.cgi?id=1748174

OAuth GitHub Provider: Organizations or Teams field is mandatory

---

pkg/env/env_test.go

Avoids side effects when running TestInitFromEnv.
InitConfig use default config (cpma.yaml) if available so we need to override all ENV variables.

env_test: force debug and silent to false

---

go.mod
pkg/transform/oauth/github.go

This reverts commit cc21ebc1a23637d556af031e0103046f0993ba7c.
If the fields are missing it will stop no only github provider transform but the whole OAuth.
To be replaced by a new patch.

Revert "OAuth GitHub Provider: Organizations or Teams field is mandatry (#389)"

---

pkg/transform/oauth/github.go

MappingMethod is optional.
If missing, it will be automatically added with default "claim" value.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1753152

OAuth Github: Mapping method is optional

---

pkg/transform/oauth/basicauth.go
pkg/transform/oauth/github.go
pkg/transform/oauth/gitlab.go
pkg/transform/oauth/google.go
pkg/transform/oauth/htpasswd.go
pkg/transform/oauth/keystone.go
pkg/transform/oauth/openid.go
pkg/transform/oauth/templates.go
pkg/transform/secrets/secrets.go
pkg/transform/secrets/secrets_test.go
pkg/transform/testdata/expected-CR-secret-github-secret.yaml
pkg/transform/testdata/expected-CR-secret-gitlab-secret.yaml
pkg/transform/testdata/expected-CR-secret-google.yaml
pkg/transform/testdata/expected-CR-secret-openid.yaml
pkg/transform/testdata/expected-CR-secret-templates-error-secret.yaml
pkg/transform/testdata/expected-CR-secret-templates-login-secret.yaml
pkg/transform/testdata/expected-CR-secret-templates-providerselect-secret.yaml

(cherry picked from commit a89d3cdf3518e6fca2a2e68ef35466ed1356cae1)

[Release-1.0] - Backport: Fix double encoding for oauth secrets (#406)

---

pkg/transform/oauth_transform.go
pkg/transform/testdata/expected-report-oauth.json

OCP4 OAuth OpenID provider has a new field dubbed "issuer" [1].
Meanwhile the field is mandatory and cannot be empty ("").
Using the "self-issued" value [2] allows creation. 
[1] https://docs.openshift.com/container-platform/4.1/authentication/identity_providers/configuring-oidc-identity-provider.html#identity-provider-oidc-CR_configuring-oidc-identity-provider
[2] https://openid.net/specs/openid-connect-core-1_0.html#SelfIssued
fixes https://github.com/fusor/cpma/issues/413
https://bugzilla.redhat.com/show_bug.cgi?id=1755865

Report about OpenID issuer field 

---

pkg/transform/apicert/apicert.go
pkg/transform/oauth/basicauth.go
pkg/transform/oauth/github.go
pkg/transform/oauth/gitlab.go
pkg/transform/oauth/google.go
pkg/transform/oauth/htpasswd.go
pkg/transform/oauth/keystone.go
pkg/transform/oauth/openid.go
pkg/transform/oauth/templates.go
pkg/transform/oauth_transform.go
pkg/transform/secrets/secrets.go
pkg/transform/secrets/secrets_test.go
pkg/transform/testdata/expected-CR-secret-basicauth-client-cert-secret.yaml
pkg/transform/testdata/expected-CR-secret-basicauth-client-key-secret.yaml

Adds `new()` creating the secret using SecretType and Data as parameters.
The main driver is because `corev1.Secret.Data` field is a map[string][]byte which key is variable, for instance with `basicAuth` it's expected to be the name of the cert or key file.
Also renames: 
- `secrets.GenTLSSecret` to `secrets.TLS`
- `secrets.GenSecret` to `secrets.Opaque`
Fixes  https://bugzilla.redhat.com/show_bug.cgi?id=1760875

Secrets: add common base and handle data name by param

---

pkg/transform/configmaps/configmaps.go
pkg/transform/configmaps/configmaps_test.go
pkg/transform/oauth/basicauth.go
pkg/transform/oauth/github.go
pkg/transform/oauth/gitlab.go
pkg/transform/oauth/keystone.go
pkg/transform/oauth/ldap.go
pkg/transform/oauth/oauth.go
pkg/transform/oauth/requestheader.go
pkg/transform/oauth_transform.go
pkg/transform/testdata/expected-CR-configmap-basicauth.yaml
pkg/transform/testdata/expected-CR-configmap-github.yaml
pkg/transform/testdata/expected-CR-configmap-gitlab.yaml
pkg/transform/testdata/expected-CR-configmap-keystone.yaml
pkg/transform/testdata/expected-CR-configmap-ldap.yaml
pkg/transform/testdata/expected-CR-configmap-requestheader.yaml
pkg/transform/testdata/expected-CR-configmap.yaml
pkg/transform/transform.go
pkg/transform/transform_test.go

(cherry picked from commit fa9a7dd6aaf4c0fd052de82229018b0e7ed63eef)

ConfigMaps use k8s definition; data uses ca.crt (#418)

---

pkg/transform/oauth/basicauth.go
pkg/transform/testdata/expected-CR-secret-basicauth-client-cert-secret.yaml
pkg/transform/testdata/expected-CR-secret-basicauth-client-key-secret.yaml

Unfortunately OCP 4 doco isn't aligned with OCP behaviour.
https://bugzilla.redhat.com/show_bug.cgi?id=1760875

BasicAuth provider secret: specific names for data fields

---

docs/README.md
pkg/transform/crio_transform.go
pkg/transform/crio_transform_test.go
pkg/transform/testdata/crio.conf

Machine Configuration Operator has dropped `InfraImage` option.
As crio.conf uses tables filter to the `runtime` subtable.

CRIO: OCP 4.2 support

---

docs/README.md
pkg/transform/crio_transform.go
pkg/transform/crio_transform_test.go
pkg/transform/testdata/crio.conf

(cherry picked from commit 295c63b1d5c0d68a01bbc263dee1013a2e687671)

CRIO: Support for runtime table; removed unsupported field (#426)

---

pkg/api/initclient.go
pkg/api/k8s.go
pkg/api/openshift.go

Using Once is overkill as we actually use variables to reference our API clients.
Also let's use client-go library to handle init or die approach.
This is to also help clearing path for dual connections to src/dst clusters at same time.

Api init refactor

---

pkg/api/initclient.go
pkg/api/k8s.go
pkg/api/requests.go
pkg/env/env.go

There is no need to create a dedicated discovery client as the default k8s client structure contains discovery.

Discovery included

---

cmd/root.go
pkg/api/initclient.go
pkg/api/requests.go
pkg/env/clusterdiscovery/clusterdiscovery.go
pkg/env/env.go
pkg/env/env_test.go
pkg/env/testdata/cpma-config.yml
pkg/transform/cluster_transform.go
test/e2e/e2e_test.go

- Makes API requests independent of client by passing the client set as paramater
- Adds survey to add destination cluster based on Kubeconfig config
- Creates destination cluster by swapping kubeconfig context

More generic API requests using client as param

---

pkg/api/requests.go
pkg/transform/cluster/cluster.go
pkg/transform/cluster/cluster_test.go
pkg/transform/cluster_transform.go
pkg/transform/internal/test/load_cluster.go

When using a target Cluster, reports the GroupVersions available in target but not in the source cluster:
```golang
"newGroupVersions": [
{
"groupversion": "apiregistration.k8s.io/v1"
},
{
"groupversion": "apps/v1"
},
{
"groupversion": "apps/v1beta2"
},
{
"groupversion": "events.k8s.io/v1beta1"
},
{
"groupversion": "autoscaling/v2beta1"
},
{
"groupversion": "autoscaling/v2beta2"
},
...<snip>...
{
"groupversion": "machine.openshift.io/v1beta1"
},
{
"groupversion": "metrics.k8s.io/v1beta1"
}```

Reports source cluster missing GroupVersions compared to target cluster

---

pkg/env/clusterdiscovery/clusterdiscovery.go
pkg/env/env.go

* run surveyHostname first to simplify
* Cluster name is prompted only when not using Kubeconfig
* Remove unused and not needed code
(cherry picked from commit 51c9cfffc5a12f159fbee8d2b4de15ce966c2d92)

Cleanse survey hostname api (#431)

---

pkg/transform/cluster_transform.go

This reverts commit 2b69781d61e24f2d4a701cc6f7eca639679a468c.
Removing discovery and GroupVersion reporting which are an unsupported feature.

Revert "Remove debug fmt (#439)"

---

pkg/api/requests.go
pkg/transform/cluster/cluster.go
pkg/transform/cluster/cluster_test.go
pkg/transform/cluster_transform.go
pkg/transform/internal/test/load_cluster.go

This reverts commit a699918a7b11382b95d56616eb8d5fbea048c41f.
Removing discovery and GroupVersion reporting which are an unsupported feature.

Revert "Reports source cluster missing GroupVersions compared to target cluster (#438)"

---

pkg/env/clusterdiscovery/clusterdiscovery.go
pkg/transform/cluster_transform.go

This reverts commit d9aa635542a6cdd6bf337139d2ec2a3bd45408f5.
Removing discovery and GroupVersion reporting which are an unsupported feature.

Revert "Discover dst cluster extra test and cleanup (#437)"

---

pkg/api/initclient.go
pkg/api/k8s.go
pkg/api/requests.go
pkg/env/env.go

This reverts commit 35d037ea729d3805130279e858366e520a677bda.
Removing discovery and GroupVersion reporting which are an unsupported feature.

Revert "Discovery is included in k8s client (#435)"

---

pkg/api/requests.go

* API Requests: Use more consistent alias names for import
* API Requests: Use more consistent alias names for o7t
(cherry picked from commit b3c236c6a7a724ee2ced3766a9431a5c37460ccc)

API Requests: Use more consistent alias names for import (#440)
